// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace db_namespace
{
    public partial class dbContextModel
    {
        partial void Initialize()
        {
            var archive = ArchiveEntityType.Create(this);
            var chat = ChatEntityType.Create(this);
            var user = UserEntityType.Create(this);
            var userData = UserDataEntityType.Create(this);

            UserEntityType.CreateForeignKey1(user, userData);

            ArchiveEntityType.CreateAnnotations(archive);
            ChatEntityType.CreateAnnotations(chat);
            UserEntityType.CreateAnnotations(user);
            UserDataEntityType.CreateAnnotations(userData);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "7.0.0-preview.6.22329.4");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
