// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using db_namespace;

#nullable disable

namespace franko_bot.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.6.22329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("db_namespace.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Faculty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Біологічний факультет"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Географічний факультет"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Геологічний факультет"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Економічний факультет"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Історичний факультет"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Механіко-математичний факультет"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Факультет електроніки та комп’ютерних технологій"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Факультет журналістики"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Факультет іноземних мов"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Факультет культури і мистецтв"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Факультет міжнародних відносин"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Факультет педагогічної освіти"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Факультет прикладної математики та інформатики"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Факультет управління фінансами та бізнесу"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Фізичний факультет"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Філологічний факультет"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Філософський факультет"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Хімічний факультет"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Юридичний факультет"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Черкаське навчально-наукове відділення"
                        });
                });

            modelBuilder.Entity("db_namespace.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Speciality");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "091",
                            FacultyId = 1,
                            Name = "Біологія"
                        },
                        new
                        {
                            Id = 2,
                            Code = "162",
                            FacultyId = 1,
                            Name = "Біотехнології та біоінженерія"
                        },
                        new
                        {
                            Id = 3,
                            Code = "101",
                            FacultyId = 1,
                            Name = "Екологія"
                        },
                        new
                        {
                            Id = 4,
                            Code = "014",
                            FacultyId = 1,
                            Name = "Середня освіта/Середня освіта (біологія та здоров’я людини)"
                        },
                        new
                        {
                            Id = 5,
                            Code = "106",
                            FacultyId = 2,
                            Name = "Географія"
                        },
                        new
                        {
                            Id = 6,
                            Code = "106",
                            FacultyId = 2,
                            Name = "Географія/Економічна і соціальна географія"
                        },
                        new
                        {
                            Id = 7,
                            Code = "106",
                            FacultyId = 2,
                            Name = "Географія/Урбаністика, просторове планування і регіональний розвиток"
                        },
                        new
                        {
                            Id = 8,
                            Code = "241",
                            FacultyId = 2,
                            Name = "Готельно-ресторанна справа"
                        },
                        new
                        {
                            Id = 9,
                            Code = "103",
                            FacultyId = 2,
                            Name = "Науки про Землю/Геоекологія і прикладна геоморфологія"
                        },
                        new
                        {
                            Id = 10,
                            Code = "103",
                            FacultyId = 2,
                            Name = "Науки про Землю/Ґрунтознавство та експертна оцінка земель"
                        },
                        new
                        {
                            Id = 11,
                            Code = "014",
                            FacultyId = 2,
                            Name = "Середня освіта/Середня освіта (Географія)"
                        },
                        new
                        {
                            Id = 12,
                            Code = "242",
                            FacultyId = 2,
                            Name = "Туризм/Туристична діяльність"
                        },
                        new
                        {
                            Id = 13,
                            Code = "181",
                            FacultyId = 2,
                            Name = "Харчові технології"
                        },
                        new
                        {
                            Id = 14,
                            Code = "103",
                            FacultyId = 3,
                            Name = "Науки про Землю/Геологія. Комп’ютерні технології в науках про Землю"
                        },
                        new
                        {
                            Id = 15,
                            Code = "103",
                            FacultyId = 3,
                            Name = "Науки про Землю/Геотехнічний та екологічний інжиніринг"
                        },
                        new
                        {
                            Id = 16,
                            Code = "051",
                            FacultyId = 4,
                            Name = "Економіка/Бізнес-економіка"
                        },
                        new
                        {
                            Id = 17,
                            Code = "051",
                            FacultyId = 4,
                            Name = "Економіка/Економіка та правове регулювання в бізнесі"
                        },
                        new
                        {
                            Id = 18,
                            Code = "051",
                            FacultyId = 4,
                            Name = "Економіка/Економічна аналітика та бізнес-статистика"
                        },
                        new
                        {
                            Id = 19,
                            Code = "051",
                            FacultyId = 4,
                            Name = "Економіка/Економічна кібернетика"
                        },
                        new
                        {
                            Id = 20,
                            Code = "051",
                            FacultyId = 4,
                            Name = "Економіка/Міжнародна економіка"
                        },
                        new
                        {
                            Id = 21,
                            Code = "075",
                            FacultyId = 4,
                            Name = "Маркетинг"
                        },
                        new
                        {
                            Id = 22,
                            Code = "073",
                            FacultyId = 4,
                            Name = "Менеджмент/Менеджмент організацій і адміністрування"
                        },
                        new
                        {
                            Id = 23,
                            Code = "073",
                            FacultyId = 4,
                            Name = "Менеджмент/Менеджмент організацій і адміністрування. Інформаційні системи у менеджмент"
                        },
                        new
                        {
                            Id = 24,
                            Code = "071",
                            FacultyId = 4,
                            Name = "Облік і оподаткування/Діджитал облік, бізнес-консалтинг і аудит"
                        },
                        new
                        {
                            Id = 25,
                            Code = "071",
                            FacultyId = 4,
                            Name = "Облік і оподаткування/Облік, аналіз і оподаткування в бізнесі"
                        },
                        new
                        {
                            Id = 26,
                            Code = "076",
                            FacultyId = 4,
                            Name = "Підприємництво, торгівля та біржова діяльність"
                        },
                        new
                        {
                            Id = 27,
                            Code = "072",
                            FacultyId = 4,
                            Name = "Фінанси, банківська справа та страхування"
                        },
                        new
                        {
                            Id = 28,
                            Code = "032",
                            FacultyId = 5,
                            Name = "Історія та археологія"
                        },
                        new
                        {
                            Id = 29,
                            Code = "014",
                            FacultyId = 5,
                            Name = "Середня освіта/Середня освіта (Історія)"
                        },
                        new
                        {
                            Id = 30,
                            Code = "054",
                            FacultyId = 5,
                            Name = "Соціологія/Прикладна соціологія. Бізнес-соціологія"
                        },
                        new
                        {
                            Id = 31,
                            Code = "111",
                            FacultyId = 6,
                            Name = "Математика/Комп’ютерна алгебра, криптологія та теорія ігор"
                        },
                        new
                        {
                            Id = 32,
                            Code = "111",
                            FacultyId = 6,
                            Name = "Математика/Комп’ютерний аналіз математичних моделей"
                        },
                        new
                        {
                            Id = 33,
                            Code = "111",
                            FacultyId = 6,
                            Name = "Математика/Математика. Математична економіка та економетрика"
                        },
                        new
                        {
                            Id = 34,
                            Code = "111",
                            FacultyId = 6,
                            Name = "Математика/Фінансова та страхова математика"
                        },
                        new
                        {
                            Id = 35,
                            Code = "113",
                            FacultyId = 6,
                            Name = "Прикладна математика/Математичне моделювання та комп’ютерна механіка"
                        },
                        new
                        {
                            Id = 36,
                            Code = "014",
                            FacultyId = 6,
                            Name = "Середня освіта/Середня освіта (Математика)"
                        },
                        new
                        {
                            Id = 37,
                            Code = "112",
                            FacultyId = 6,
                            Name = "Статистика/Статистичний аналіз даних"
                        },
                        new
                        {
                            Id = 38,
                            Code = "121",
                            FacultyId = 20,
                            Name = "Інженерія програмного забезпечення"
                        },
                        new
                        {
                            Id = 39,
                            Code = "073",
                            FacultyId = 20,
                            Name = "Менеджмент"
                        },
                        new
                        {
                            Id = 40,
                            Code = "071",
                            FacultyId = 20,
                            Name = "Облік і оподаткування"
                        },
                        new
                        {
                            Id = 41,
                            Code = "081",
                            FacultyId = 20,
                            Name = "Право"
                        },
                        new
                        {
                            Id = 42,
                            Code = "072",
                            FacultyId = 20,
                            Name = "Фінанси, банківська справа та страхування"
                        },
                        new
                        {
                            Id = 43,
                            Code = "171",
                            FacultyId = 7,
                            Name = "Електроніка/Електроніка та комп’ютерні системи"
                        },
                        new
                        {
                            Id = 44,
                            Code = "121",
                            FacultyId = 7,
                            Name = "Інженерія програмного забезпечення/Високопродуктивний комп’ютинг"
                        },
                        new
                        {
                            Id = 45,
                            Code = "121",
                            FacultyId = 7,
                            Name = "Інженерія програмного забезпечення"
                        },
                        new
                        {
                            Id = 46,
                            Code = "126",
                            FacultyId = 7,
                            Name = "Інформаційні системи та технології"
                        },
                        new
                        {
                            Id = 47,
                            Code = "122",
                            FacultyId = 7,
                            Name = "Комп’ютерні науки"
                        },
                        new
                        {
                            Id = 48,
                            Code = "153",
                            FacultyId = 7,
                            Name = "Мікро- та наносистемна техніка/Сенсорні та діагностичні електронні системи"
                        },
                        new
                        {
                            Id = 49,
                            Code = "061",
                            FacultyId = 8,
                            Name = "Журналістика"
                        },
                        new
                        {
                            Id = 50,
                            Code = "035",
                            FacultyId = 9,
                            Name = "Філологія/Філологія (Германські мови та літератури (переклад включно), перша – англійська: переклад (англійська та друга іноземні мови))"
                        },
                        new
                        {
                            Id = 51,
                            Code = "035",
                            FacultyId = 9,
                            Name = "Філологія/Філологія (Германські мови та літератури (переклад включно), перша – німецька: німецька та англійська мови і літератури (переклад включно))"
                        },
                        new
                        {
                            Id = 52,
                            Code = "035",
                            FacultyId = 9,
                            Name = "Філологія/Філологія (Германські мови та літератури (переклад включно), перша – англійська: англійська та друга іноземні мови і літератури)"
                        },
                        new
                        {
                            Id = 53,
                            Code = "035",
                            FacultyId = 9,
                            Name = "Філологія/Філологія (Германські мови та літератури (переклад включно), перша – німецька: переклад (німецька і друга іноземна мови, міжкультурна комунікація))"
                        },
                        new
                        {
                            Id = 54,
                            Code = "035",
                            FacultyId = 9,
                            Name = "Філологія/Філологія (Класичні мови та літератури (переклад включно): класична філологія і англійська мова)"
                        },
                        new
                        {
                            Id = 55,
                            Code = "035",
                            FacultyId = 9,
                            Name = "Філологія/Філологія (Романські мови та літератури (переклад включно), перша – іспанська: іспанська та англійська мови і літератури)"
                        },
                        new
                        {
                            Id = 56,
                            Code = "035",
                            FacultyId = 9,
                            Name = "Філологія/Філологія (Романські мови та літератури (переклад включно), перша – французька: французька та англійська мови і літератури)"
                        },
                        new
                        {
                            Id = 57,
                            Code = "029",
                            FacultyId = 10,
                            Name = "Інформаційна, бібліотечна та архівна справа"
                        },
                        new
                        {
                            Id = 58,
                            Code = "028",
                            FacultyId = 10,
                            Name = "Менеджмент соціокультурної діяльності"
                        },
                        new
                        {
                            Id = 59,
                            Code = "025",
                            FacultyId = 10,
                            Name = "Музичне мистецтво/Хорове диригування"
                        },
                        new
                        {
                            Id = 60,
                            Code = "014",
                            FacultyId = 10,
                            Name = "Середня освіта/Середня освіта (Музичне мистецтво)"
                        },
                        new
                        {
                            Id = 61,
                            Code = "026",
                            FacultyId = 10,
                            Name = "Сценічне мистецтво/Акторське мистецтво драматичного театру та кіно"
                        },
                        new
                        {
                            Id = 62,
                            Code = "026",
                            FacultyId = 10,
                            Name = "Сценічне мистецтво/Театрознавство"
                        },
                        new
                        {
                            Id = 63,
                            Code = "024",
                            FacultyId = 10,
                            Name = "Хореографія"
                        },
                        new
                        {
                            Id = 64,
                            Code = "293",
                            FacultyId = 11,
                            Name = "Міжнародне право"
                        },
                        new
                        {
                            Id = 65,
                            Code = "291",
                            FacultyId = 11,
                            Name = "Міжнародні відносини, суспільні комунікації та регіональні студії/Країнознавство"
                        },
                        new
                        {
                            Id = 66,
                            Code = "291",
                            FacultyId = 11,
                            Name = "Міжнародні відносини, суспільні комунікації та регіональні студії/Міжнародна безпека та кризовий менеджмент"
                        },
                        new
                        {
                            Id = 67,
                            Code = "291",
                            FacultyId = 11,
                            Name = "Міжнародні відносини, суспільні комунікації та регіональні студії/Міжнародна інформація"
                        },
                        new
                        {
                            Id = 68,
                            Code = "291",
                            FacultyId = 11,
                            Name = "Міжнародні відносини, суспільні комунікації та регіональні студії/Міжнародні відносини"
                        },
                        new
                        {
                            Id = 69,
                            Code = "292",
                            FacultyId = 11,
                            Name = "Міжнародні економічні відносини/Міжнародний бізнес"
                        },
                        new
                        {
                            Id = 70,
                            Code = "292",
                            FacultyId = 11,
                            Name = "Міжнародні економічні відносини"
                        },
                        new
                        {
                            Id = 71,
                            Code = "012",
                            FacultyId = 12,
                            Name = "Дошкільна освіта"
                        },
                        new
                        {
                            Id = 72,
                            Code = "011",
                            FacultyId = 12,
                            Name = "Освітні, педагогічні науки/Організація освітнього простору. Позашкільна освіта."
                        },
                        new
                        {
                            Id = 73,
                            Code = "013",
                            FacultyId = 12,
                            Name = "Початкова освіта"
                        },
                        new
                        {
                            Id = 74,
                            Code = "013",
                            FacultyId = 12,
                            Name = "Початкова освіта/Початкова освіта. Англійська мова у початковій школі"
                        },
                        new
                        {
                            Id = 75,
                            Code = "013",
                            FacultyId = 12,
                            Name = "Початкова освіта/Початкова освіта. Інформатика у початковій школі"
                        },
                        new
                        {
                            Id = 76,
                            Code = "231",
                            FacultyId = 12,
                            Name = "Соціальна робота/Соціальна педагогіка"
                        },
                        new
                        {
                            Id = 77,
                            Code = "016",
                            FacultyId = 12,
                            Name = "Спеціальна освіта/Логопедія"
                        },
                        new
                        {
                            Id = 78,
                            Code = "016",
                            FacultyId = 12,
                            Name = "Спеціальна освіта/Олігофренопедагогіка. Корекційна психопедагогіка"
                        },
                        new
                        {
                            Id = 79,
                            Code = "125",
                            FacultyId = 13,
                            Name = "Кібербезпека/Кібербезпека. Кіберпезпека у фінансових технологіях"
                        },
                        new
                        {
                            Id = 80,
                            Code = "122",
                            FacultyId = 13,
                            Name = "Комп’ютерні науки/Інформатика"
                        },
                        new
                        {
                            Id = 81,
                            Code = "113",
                            FacultyId = 13,
                            Name = "Прикладна математика"
                        },
                        new
                        {
                            Id = 82,
                            Code = "014",
                            FacultyId = 13,
                            Name = "Середня освіта/Середня освіта (Інформатика)"
                        },
                        new
                        {
                            Id = 83,
                            Code = "124",
                            FacultyId = 13,
                            Name = "Системний аналіз/Системний аналіз і управління. Інтелектуальний аналіз даних"
                        },
                        new
                        {
                            Id = 84,
                            Code = "051",
                            FacultyId = 14,
                            Name = "Економіка/Інформаційні технології в бізнесі"
                        },
                        new
                        {
                            Id = 85,
                            Code = "071",
                            FacultyId = 14,
                            Name = "Облік і оподаткування/Облік, аналіз та фінансові розслідування"
                        },
                        new
                        {
                            Id = 86,
                            Code = "281",
                            FacultyId = 14,
                            Name = "Публічне управління та адміністрування/Публічне адміністрування та управління бізнесом"
                        },
                        new
                        {
                            Id = 87,
                            Code = "281",
                            FacultyId = 14,
                            Name = "Публічне управління та адміністрування/Публічне управління та адміністрування. Управління персоналом в органах публічної влади та бізнес-структурах"
                        },
                        new
                        {
                            Id = 88,
                            Code = "072",
                            FacultyId = 14,
                            Name = "Фінанси, банківська справа та страхування/Фінанси, митна та податкова справа"
                        },
                        new
                        {
                            Id = 89,
                            Code = "072",
                            FacultyId = 14,
                            Name = "Фінанси, банківська справа та страхування/Фінансовий менеджмент"
                        },
                        new
                        {
                            Id = 90,
                            Code = "105",
                            FacultyId = 15,
                            Name = "Прикладна фізика та наноматеріали/Комп’ютерні технології в прикладній фізиці. Нанофізика та наноматеріали"
                        },
                        new
                        {
                            Id = 91,
                            Code = "014",
                            FacultyId = 15,
                            Name = "Середня освіта/Середня освіта (Фізика)"
                        },
                        new
                        {
                            Id = 92,
                            Code = "104",
                            FacultyId = 15,
                            Name = "Фізика та астрономія/Квантові комп’ютери та квантове програмування"
                        },
                        new
                        {
                            Id = 93,
                            Code = "104",
                            FacultyId = 15,
                            Name = "Фізика та астрономія/Комп’ютерна фізика"
                        },
                        new
                        {
                            Id = 94,
                            Code = "104",
                            FacultyId = 15,
                            Name = "Фізика та астрономія/Фізика та астрофізика"
                        },
                        new
                        {
                            Id = 95,
                            Code = "014",
                            FacultyId = 16,
                            Name = "Середня освіта/Середня освіта (Українська мова і література)"
                        },
                        new
                        {
                            Id = 96,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Арабська мова та література, українська мова та література"
                        },
                        new
                        {
                            Id = 97,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Болгарська мова та література"
                        },
                        new
                        {
                            Id = 98,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Китайська мова та література, українська мова та література"
                        },
                        new
                        {
                            Id = 99,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Перська мова та література, українська мова та література"
                        },
                        new
                        {
                            Id = 100,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Польська мова та література"
                        },
                        new
                        {
                            Id = 101,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Прикладна лінгвістика"
                        },
                        new
                        {
                            Id = 102,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Українська мова та література"
                        },
                        new
                        {
                            Id = 103,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Українська мова та література (Літературна творчість)"
                        },
                        new
                        {
                            Id = 104,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Українська мова та література, українська мова як іноземна"
                        },
                        new
                        {
                            Id = 105,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Фольклористика"
                        },
                        new
                        {
                            Id = 106,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Хорватська мова та література"
                        },
                        new
                        {
                            Id = 107,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Чеська мова та література"
                        },
                        new
                        {
                            Id = 108,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Японська мова та література, українська мова та література"
                        },
                        new
                        {
                            Id = 109,
                            Code = "014",
                            FacultyId = 16,
                            Name = "Середня освіта/Середня освіта (Українська мова і література)"
                        },
                        new
                        {
                            Id = 110,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Арабська мова та література, українська мова та література"
                        },
                        new
                        {
                            Id = 111,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Болгарська мова та література"
                        },
                        new
                        {
                            Id = 112,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Китайська мова та література, українська мова та література"
                        },
                        new
                        {
                            Id = 113,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Перська мова та література, українська мова та література"
                        },
                        new
                        {
                            Id = 114,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Польська мова та література"
                        },
                        new
                        {
                            Id = 115,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Прикладна лінгвістика"
                        },
                        new
                        {
                            Id = 116,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Українська мова та література"
                        },
                        new
                        {
                            Id = 117,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Українська мова та література (Літературна творчість)"
                        },
                        new
                        {
                            Id = 118,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Українська мова та література, українська мова як іноземна"
                        },
                        new
                        {
                            Id = 119,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Фольклористика"
                        },
                        new
                        {
                            Id = 120,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Хорватська мова та література"
                        },
                        new
                        {
                            Id = 121,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Чеська мова та література"
                        },
                        new
                        {
                            Id = 122,
                            Code = "035",
                            FacultyId = 16,
                            Name = "Філологія/Японська мова та література, українська мова та література"
                        },
                        new
                        {
                            Id = 123,
                            Code = "014",
                            FacultyId = 18,
                            Name = "Середня освіта/Середня освіта (Хімія)"
                        },
                        new
                        {
                            Id = 124,
                            Code = "102",
                            FacultyId = 18,
                            Name = "Хімія"
                        },
                        new
                        {
                            Id = 125,
                            Code = "081",
                            FacultyId = 19,
                            Name = "Право"
                        });
                });

            modelBuilder.Entity("db_namespace.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<int>("FacultyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("db_namespace.Speciality", b =>
                {
                    b.HasOne("db_namespace.Faculty", "Faculty")
                        .WithMany("Specialities")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("db_namespace.User", b =>
                {
                    b.HasOne("db_namespace.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db_namespace.Speciality", "Speciality")
                        .WithMany()
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("db_namespace.Faculty", b =>
                {
                    b.Navigation("Specialities");
                });
#pragma warning restore 612, 618
        }
    }
}
