// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace BotSettings
{
    [DbContext(typeof(InMemoryContext))]
    public partial class InMemoryContextModel : RuntimeModel
    {
        static InMemoryContextModel()
        {
            var model = new InMemoryContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static InMemoryContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
