// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace BotSettings
{
    public partial class InMemoryContextModel
    {
        partial void Initialize()
        {
            var stageModel = StageModelEntityType.Create(this);

            StageModelEntityType.CreateAnnotations(stageModel);

            AddAnnotation("ProductVersion", "7.0.0-preview.6.22329.4");
        }
    }
}
